export const Homecart = [
    {   id: 1,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/chair.jpg",
        name: "Norwegg Chair",
        price: 121.00,
        category: "Table",
    },
    {   id: 2,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/book.jpg",
        name: "Book Chair",
        price: 154.00,
        category: "Book",
    },
    {   id: 3,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/chair2.jpg",
        name: "Another chair",
        price: 1230.00,
        category: "Table",
    },
    {   id: 4,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/chair3.jpg",
        name: "Your new chair",
        price: 32.00,
        category: "Table",
    },
    {   id: 5,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/clock.jpg",
        name: "Clock",
        price: 12.00,
        category: "Hour",
    },
    {   id: 6,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/clock3.jpg",
        name: "Clock",
        price: 30.00,
        category: "Hour",
    },
    {   id: 7,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/box.jpg",
        name: "Accessory box",
        price: 420.00,
        category: "Basket",
    },
    {   id: 8,
        img: "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/box2.jpg",
        name: "Beige",
        price: 140.00,
        category: "Basket",
    },
   
]