export const Homecart = [
    {   "id": 1,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/chair.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 2,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/book.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 3,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/chair2.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 1,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/chair3.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 1,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/clock.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 1,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/clock3.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 1,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/box.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
    {   "id": 1,
        "img": "https://d19m59y37dris4.cloudfront.net/varkala/1-2-1/img/product/box2.jpg",
        "name": "Norwegg Chair",
        "price": "$40.00",
    },
   
]